---
title: "RWorksheet_Analytics"
author: "Tamayo,Salinas, Loredo, Amuan, & Juntanilla"
date: "2023-12-09"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
URL and libraries
```{r}
library(rvest)
library(dplyr)
library(polite)
library(stringr)
url <- "https://www.imdb.com/chart/toptv/?ref_=nv_tvv_250"

session <- bow(url,user_agent = "Educational Purposes")
session

```
1.
```{r}
#title and ranks
library(rvest)
title <- scrape(session)%>%
html_nodes("h3.ipc-title__text")%>%
html_text
title

#subset title
subsettt <- as.data.frame(title[2:51])

colnames(subsettt) <- "ranks"
split_df <- strsplit(as.character(subsettt$ranks), ".", fixed = TRUE )
split_df<- data.frame(do.call(rbind, split_df))
#remove duplicate columns
split_df <- split_df[-c(3:5)]
#rename columns
colnames(split_df) <- c("ranks","title") 
split_df
#make into a data frame
mekdf <- as.data.frame(split_df)
mekdf


#scraping the imdb rating
rate <- scrape(session) %>%
  html_nodes("span.ipc-rating-star--imdb")  %>%
html_attr("aria-label")
rate
#subset the scraped data
rate_sub<- as.data.frame(rate[2:51])
head(rate_sub)
#renaming the column
colnames(rate_sub) <- "rate"
split_df3 <- strsplit(as.character(rate_sub$rate),".",fixed = TRUE)
split_df3 <- data.frame(do.call(rbind,split_df))
#extract only the ratings
ratings<- str_extract(rate_sub$rate, "\\d+\\.\\d+")
ratings
#make this into a data frame
rates <- as.data.frame(ratings)

#scraping vote counts
votec <- scrape(session) %>%
  html_nodes("span.ipc-rating-star--voteCount") %>%
  html_text
#subset the scraped data of vote counts
subvote <- as.data.frame(votec[1:50])
#renaming columns
colnames(subvote) <- "votecount"
split_df2 <- strsplit(as.character(subvote$voteCount), ".", fixed = TRUE )
split_df2 <- data.frame(do.call(rbind, subvote))
subvote


#Scrape the year and episodes
shesh <- read_html(url)

# Extract the HTML structure of the div class
div_elements <- shesh %>%
  html_nodes("div.sc-43986a27-7.dBkaPT.cli-title-metadata")

# Create an empty list to store the extracted information
results_list <- list()

# Loop through each div element
for (i in 1:min(length(div_elements), 50)) {
  # Extract all span elements within each div
  spans <- div_elements[i] %>%
    html_nodes("span.sc-43986a27-8.jHYIIK.cli-title-metadata-item")

  # Extract and store the text from each span
  span_texts <- sapply(spans, function(span) {
    span_text <- span %>% html_text()
    return(span_text)
  })

  # Store the extracted information in the results list
  results_list[[i]] <- span_texts
}

# Convert the results list to a data frame 
results_df <- do.call(rbind.data.frame, results_list)

# Set column names based on the extracted spans 
colnames(results_df) <- paste0("span_", 1:ncol(results_df))

newcol <- c("year", "episodes", "guidance")
colnames(results_df) <- newcol
# Removing the third column
results_df <- results_df[, -which(names(results_df) == "guidance")]

# Print or return the results
print(results_df)

dataf <- as.data.frame(results_df)


# Combine in one data frame
newdata <- data.frame(
  mekdf,
 rates,
  Vote_count = subvote,
  dataf

)
newdata
```
2.
#number 2 

```{r} 
scrape_reviews <- function(url) {
  page <- read_html(url)
  title_reviews <- page %>% 
    html_nodes(".title") %>% 
    html_text()
  
  rating_reviews <- page %>% 
    html_nodes(".rating-other-user-rating") %>%
    html_text()
  
  dates_reviews <- page %>% 
    html_nodes(".review-date") %>%
    html_text()
  
  users_reviews <- page %>% 
    html_nodes(".display-name-link") %>%
    html_text()
  
  text_review <- page %>%
    html_nodes("div.text.show-more__control")%>%
    html_text()
  
  
  max_length <- max(length(title_reviews), length(rating_reviews), length(dates_reviews), length(users_reviews), length(text_review))
  
  
  Nachange <- function(x, target_length) {
    if (length(x) < target_length) {
      c(x, rep(NA, target_length - length(x)))
    } else {
      x
    }
  }
  
  
  title_reviews <- Nachange(title_reviews, max_length)
  rating_reviews <- Nachange(rating_reviews, max_length)
  dates_reviews <- Nachange(dates_reviews, max_length)
  users_reviews <- Nachange(users_reviews, max_length)
  text_review <- Nachange(text_review, max_length)
  
  # Create a data frame
  reviewsdata1 <- data.frame(
    TITLE = title_reviews,
    RATING = rating_reviews,
    DATE = dates_reviews,
    USER = users_reviews,
    USER = text_review
  )
  
  return(reviewsdata1)
}
tvshow1 <- c("https://www.imdb.com/title/tt1844624/reviews/?ref_=tt_ov_rt")
reviews1 <- scrape_reviews(tvshow1[1]) 
reviews1
```


```{r} 
scrape_reviews <- function(url) {
  page <- read_html(url)
  title_reviews <- page %>% 
    html_nodes(".title") %>% 
    html_text()
  
  rating_reviews <- page %>% 
    html_nodes(".rating-other-user-rating") %>%
    html_text()
  
  dates_reviews <- page %>% 
    html_nodes(".review-date") %>%
    html_text()
  
  users_reviews <- page %>% 
    html_nodes(".display-name-link") %>%
    html_text()
  
  text_review <- page %>%
    html_nodes("div.text.show-more__control")%>%
    html_text()
  
  
  max_length <- max(length(title_reviews), length(rating_reviews), length(dates_reviews), length(users_reviews), length(text_review))
  
  
  Nachange <- function(x, target_length) {
    if (length(x) < target_length) {
      c(x, rep(NA, target_length - length(x)))
    } else {
      x
    }
  }
  
  
  title_reviews <- Nachange(title_reviews, max_length)
  rating_reviews <- Nachange(rating_reviews, max_length)
  dates_reviews <- Nachange(dates_reviews, max_length)
  users_reviews <- Nachange(users_reviews, max_length)
  text_review <- Nachange(text_review, max_length)
  
  # Create a data frame
  reviewsdata2 <- data.frame(
    TITLE = title_reviews,
    RATING = rating_reviews,
    DATE = dates_reviews,
    USER = users_reviews,
    USER = text_review
  )
  
  return(reviewsdata2)
}
tvshow2 <- c("https://www.imdb.com/title/tt0436992/reviews/?ref_=tt_ov_rt")
reviews2 <- scrape_reviews(tvshow2[1]) 
reviews2
```

```{r} 
scrape_reviews <- function(url) {
  page <- read_html(url)
  title_reviews <- page %>% 
    html_nodes(".title") %>% 
    html_text()
  
  rating_reviews <- page %>% 
    html_nodes(".rating-other-user-rating") %>%
    html_text()
  
  dates_reviews <- page %>% 
    html_nodes(".review-date") %>%
    html_text()
  
  users_reviews <- page %>% 
    html_nodes(".display-name-link") %>%
    html_text()
  
  text_review <- page %>%
    html_nodes("div.text.show-more__control")%>%
    html_text()
  
  
  max_length <- max(length(title_reviews), length(rating_reviews), length(dates_reviews), length(users_reviews), length(text_review))
  
  
  Nachange <- function(x, target_length) {
    if (length(x) < target_length) {
      c(x, rep(NA, target_length - length(x)))
    } else {
      x
    }
  }
  
  
  title_reviews <- Nachange(title_reviews, max_length)
  rating_reviews <- Nachange(rating_reviews, max_length)
  dates_reviews <- Nachange(dates_reviews, max_length)
  users_reviews <- Nachange(users_reviews, max_length)
  text_review <- Nachange(text_review, max_length)
  
  # Create a data frame
  reviewsdata3 <- data.frame(
    TITLE = title_reviews,
    RATING = rating_reviews,
    DATE = dates_reviews,
    USER = users_reviews,
    USER = text_review
  )
  
  return(reviewsdata3)
}
tvshow3 <- c("https://www.imdb.com/title/tt12343534/reviews/?ref_=tt_ov_rt")
reviews3 <- scrape_reviews(tvshow3[1]) 
reviews3
```

```{r} 
scrape_reviews <- function(url) {
  page <- read_html(url)
  title_reviews <- page %>% 
    html_nodes(".title") %>% 
    html_text()
  
  rating_reviews <- page %>% 
    html_nodes(".rating-other-user-rating") %>%
    html_text()
  
  dates_reviews <- page %>% 
    html_nodes(".review-date") %>%
    html_text()
  
  users_reviews <- page %>% 
    html_nodes(".display-name-link") %>%
    html_text()
  
  text_review <- page %>%
    html_nodes("div.text.show-more__control")%>%
    html_text()
  
  
  max_length <- max(length(title_reviews), length(rating_reviews), length(dates_reviews), length(users_reviews), length(text_review))
  
  
  Nachange <- function(x, target_length) {
    if (length(x) < target_length) {
      c(x, rep(NA, target_length - length(x)))
    } else {
      x
    }
  }
  
  
  title_reviews <- Nachange(title_reviews, max_length)
  rating_reviews <- Nachange(rating_reviews, max_length)
  dates_reviews <- Nachange(dates_reviews, max_length)
  users_reviews <- Nachange(users_reviews, max_length)
  text_review <- Nachange(text_review, max_length)
  
  # Create a data frame
  reviewsdata4 <- data.frame(
    TITLE = title_reviews,
    RATING = rating_reviews,
    DATE = dates_reviews,
    USER = users_reviews,
    USER = text_review
  )
  
  return(reviewsdata4)
}
tvshow4 <- c("https://www.imdb.com/title/tt2861424/reviews/?ref_=tt_ov_rt")
reviews4 <- scrape_reviews(tvshow4[1]) 
reviews4
```

```{r} 
scrape_reviews <- function(url) {
  page <- read_html(url)
  title_reviews <- page %>% 
    html_nodes(".title") %>% 
    html_text()
  
  rating_reviews <- page %>% 
    html_nodes(".rating-other-user-rating") %>%
    html_text()
  
  dates_reviews <- page %>% 
    html_nodes(".review-date") %>%
    html_text()
  
  users_reviews <- page %>% 
    html_nodes(".display-name-link") %>%
    html_text()
  
  text_review <- page %>%
    html_nodes("div.text.show-more__control")%>%
    html_text()
  
  
  max_length <- max(length(title_reviews), length(rating_reviews), length(dates_reviews), length(users_reviews), length(text_review))
  
  
  Nachange <- function(x, target_length) {
    if (length(x) < target_length) {
      c(x, rep(NA, target_length - length(x)))
    } else {
      x
    }
  }
  
  
  title_reviews <- Nachange(title_reviews, max_length)
  rating_reviews <- Nachange(rating_reviews, max_length)
  dates_reviews <- Nachange(dates_reviews, max_length)
  users_reviews <- Nachange(users_reviews, max_length)
  text_review <- Nachange(text_review, max_length)
  
  # Create a data frame
  reviewsdata5 <- data.frame(
    TITLE = title_reviews,
    RATING = rating_reviews,
    DATE = dates_reviews,
    USER = users_reviews,
    USER = text_review
  )
  
  return(reviewsdata5)
}
tvshow5 <- c("https://www.imdb.com/title/tt1520211/reviews/?ref_=tt_ov_rt")
reviews5 <- scrape_reviews(tvshow5[1]) 
reviews5
```

3.
```{r}
library(ggplot2)
ggplot(dataf, 
       aes(x = year)) +
  geom_bar(stat = "count", fill = "darkblue") +
  labs(title = "TV Shows Released by Year",
       x = "Release Year",
       y = "Number of TV Shows Released") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

# Find the year with the most TV shows released
mostTvshow <- dataf %>%
  group_by(year) %>%
  summarise(total_shows = n())

mostyear <- mostTvshow$year[which.max(mostTvshow$total_shows)]

cat("The year with the most TV shows released is ", mostyear)

```

 1st product
```{r}
library(rvest)
library(stringr)
library(dplyr)


url1 <- "https://www.amazon.com/dp/B07KRY43KN/ref=s9_acsd_al_bw_c2_x_2_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=GZGJJ856P8VPY486DVX2&pf_rd_t=101&pf_rd_p=b48f1b52-3d78-40aa-8e5b-0e5b1e8f2dba&pf_rd_i=21217035011"

product1 <- read_html(url1)

#Price
price1 <- product1 %>% html_nodes("span.a-offscreen") %>% html_text() %>% .[1]

#Description
des <- product1 %>%
  html_nodes("span.a-list-item") %>%
  html_text()
descrange <- paste(des[33:37], collapse = " ")

#Review Count
rate1 <- product1 %>% html_nodes("span.a-size-base#acrCustomerReviewText") %>% html_text()
numeric_data1 <- as.numeric(gsub("\\D", "", rate1))
review_count <- format(numeric_data1[1], big.mark = ",")

#Review Text
review_text <- product1 %>% html_node("span.a-size-base.review-text") %>% html_text()
review_text <- str_replace_all(review_text, "\n", "")


data_frame <- data.frame(
  Price = price1,
  Description = descrange,
  Review_Count = review_count,
  Review_Text = review_text
)

print(data_frame)

```


2nd Product
```{r}
library(rvest)
library(stringr)
library(dplyr)


url2 <- "https://www.amazon.com/dp/B01EZV35QU/ref=s9_acsd_al_bw_c2_x_9_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=GZGJJ856P8VPY486DVX2&pf_rd_t=101&pf_rd_p=b48f1b52-3d78-40aa-8e5b-0e5b1e8f2dba&pf_rd_i=21217035011&th=1"

product2 <- read_html(url2)

#Price
price2 <- product2 %>% html_nodes("span.a-offscreen") %>% html_text() %>% .[1]

#Description
des2 <- product2 %>%
  html_nodes("span.a-list-item") %>%
  html_text()
descrange2 <- paste(des2[63:67], collapse = " ")

#Review Count
rate2 <- product2 %>% html_nodes("span.a-size-base#acrCustomerReviewText") %>% html_text()
numeric_data2 <- as.numeric(gsub("\\D", "", rate2[1]))
review_count2 <- format(numeric_data2, big.mark = ",")

#Review Text
review_text2 <- product2 %>% html_node("span.a-size-base.review-text") %>% html_text()
review_text2 <- str_replace_all(review_text2, "\n", "")


data_frame2 <- data.frame(
  Price = price2,
  Description = descrange2,
  Review_Count = review_count2,
  Review_Text = review_text2
)

#data frame
print(data_frame2)



``` 


3rd Product
```{r}
library(rvest)
library(stringr)
library(dplyr)

url3 <- "https://www.amazon.com/dp/B099WTN2TR/ref=s9_acsd_al_bw_c2_x_6_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=GZGJJ856P8VPY486DVX2&pf_rd_t=101&pf_rd_p=b48f1b52-3d78-40aa-8e5b-0e5b1e8f2dba&pf_rd_i=21217035011"

product3 <- read_html(url3)

#Price
price3 <- product3 %>% html_nodes("span.a-offscreen") %>% html_text() %>% .[1]

#Description
des3 <- product3 %>%
  html_nodes("span.a-list-item") %>%
  html_text()
descrange3 <- paste(des3[58:62], collapse = " ")

#Review Count
rate3 <- product3 %>% html_nodes("span.a-size-base#acrCustomerReviewText") %>% html_text()
numeric_data3 <- as.numeric(gsub("\\D", "", rate3))
review_count3 <- format(numeric_data3[1], big.mark = ",")

#Review Text
review_text3 <- product3 %>% html_node("span.a-size-base.review-text") %>% html_text()
review_text3 <- str_replace_all(review_text3, "\n", "")


data_frame3 <- data.frame(
  Price = price3,
  Description = descrange3,
  Review_Count = review_count3,
  Review_Text = review_text3
)

#frame
print(data_frame3)


```

```{r}

combined_data <- rbind(data_frame, data_frame2, data_frame3)

print(combined_data)


```








